on:
  pull_request:
    types:
      - closed
    branches:
      - "main"
    paths:
      - "src/dsspellchecker/**"
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GDEX deployment
        run: curl -s -o - "https://gdex.k8s.ucar.edu/redeploy/spellchecker/"
